[
  {
    id: ,
    run_name: 'Big Horn Sheep Canyon',
    river_name: 'Arkansas',
    state: 'CO',
    difficulty: ['III'],
    permit_by_lottery: false,
    season: ['May', 'Jun', 'Jul', 'Aug', 'Sept'],
    does_it_actually_run: 'This section reliably runs each summer, although it usually drops to only the native flow around mid August. During some seasons, the native flow still makes for a fun trip, but during others this will mean very low water.',
    length_in_days: [0.5, 1],
    length_in_miles: '',
    put_in: '',
    take_out: '',
    gauge: '',
    recommended_flows: '',
    img: '',
    img_credit: '',
    link_to_more_info: '',
    facts: [''],
    wild_and_scenic: false
  },
  {
    id: ,
    run_name: 'Middle Fork of the Flathead',
    river_name: '',
    state: '',
    difficulty: '',
    permit_by_lottery: ,
    season: [],
    does_it_actually_run: '',
    length_in_days: '',
    length_in_miles: '',
    put_in: '',
    take_out: '',
    gauge: '',
    recommended_flows: '',
    img: '',
    img_credit: '',
    link_to_more_info: '',
    facts: ['']
  },
  {
    id: ,
    run_name: 'Stillwater Canyon',
    river_name: '',
    state: '',
    difficulty: '',
    permit_by_lottery: ,
    season: [],
    does_it_actually_run: '',
    length_in_days: '',
    length_in_miles: '',
    put_in: '',
    take_out: '',
    gauge: '',
    recommended_flows: '',
    img: '',
    img_credit: '',
    link_to_more_info: '',
    facts: ['']
  },
  {
    id: 23,
    run_name: 'Labyrinth Canyon',
    river_name: '',
    state: '',
    difficulty: '',
    permit_by_lottery: ,
    season: [],
    does_it_actually_run: '',
    length_in_days: '',
    length_in_miles: '',
    put_in: '',
    take_out: '',
    gauge: '',
    recommended_flows: '',
    img: '',
    img_credit: '',
    link_to_more_info: '',
    facts: ['']
  },
  {
    id: 24,
    run_name: 'Dolores',
    river_name: '',
    state: '',
    difficulty: '',
    permit_by_lottery: ,
    season: [],
    does_it_actually_run: '',
    length_in_days: '',
    length_in_miles: '',
    put_in: '',
    take_out: '',
    gauge: '',
    recommended_flows: '',
    img: '',
    img_credit: '',
    link_to_more_info: '',
    facts: ['']
  },
  {
    id: 26,
    run_name: 'Illinois',
    river_name: '',
    state: ['OR'],
    difficulty: ['IV', 'IV+'],
    permit_by_lottery: ,
    season: [],
    does_it_actually_run: '',
    length_in_days: [],
    length_in_miles: 32,
    put_in: 'Miami Bar',
    take_out: 'Oak Flat',
    gauge: '',
    recommended_flows: '',
    img: '',
    img_credit: '',
    link_to_more_info: '',
    facts: [''],
    wild_and_scenic:
  },
  {
    id: 32,
    run_name: 'Flaming Gorge',
    river_name: '',
    state: [''],
    difficulty: '',
    permit_by_lottery: ,
    season: [],
    does_it_actually_run: '',
    length_in_days: [],
    length_in_miles: ,
    put_in: '',
    take_out: '',
    gauge: '',
    recommended_flows: '',
    img: '',
    img_credit: '',
    link_to_more_info: '',
    facts: [''],
    wild_and_scenic:
  },
  {
    id: 35,
    run_name: 'Chattooga ()',
    river_name: '',
    state: [''],
    difficulty: '',
    permit_by_lottery: ,
    season: [],
    does_it_actually_run: '',
    length_in_days: [],
    length_in_miles: ,
    put_in: '',
    take_out: '',
    gauge: '',
    recommended_flows: '',
    img: '',
    img_credit: '',
    link_to_more_info: '',
    facts: [''],
    wild_and_scenic:
  },
  {
    id: 36,
    run_name: 'Chattooga ()',
    river_name: '',
    state: [''],
    difficulty: '',
    permit_by_lottery: ,
    season: [],
    does_it_actually_run: '',
    length_in_days: [],
    length_in_miles: ,
    put_in: '',
    take_out: '',
    gauge: '',
    recommended_flows: '',
    img: '',
    img_credit: '',
    link_to_more_info: '',
    facts: [''],
    wild_and_scenic:
  },
  {
    id: 37,
    run_name: 'John Day',
    river_name: 'John Day River',
    state: ['OR'],
    difficulty: ['II', 'III'],
    permit_by_lottery: ,
    season: ['Apr', 'May', 'Jun'],
    does_it_actually_run: '',
    length_in_days: [],
    length_in_miles: 68,
    put_in: 'Clarno',
    take_out: 'Cottonwood',
    gauge: '',
    recommended_flows: {
      minimum: '1200 cfs',
      maximum: '6000 cfs'
    },
    img: '',
    img_credit: '',
    link_to_more_info: '',
    facts: [''],
    wild_and_scenic:
  },
  {
    id: 38,
    run_name: 'Nolichucky',
    river_name: '',
    state: [''],
    difficulty: '',
    permit_by_lottery: ,
    season: [],
    does_it_actually_run: '',
    length_in_days: [],
    length_in_miles: ,
    put_in: '',
    take_out: '',
    gauge: '',
    recommended_flows: '',
    img: '',
    img_credit: '',
    link_to_more_info: '',
    facts: [''],
    wild_and_scenic:
  },
  {
    id: 39,
    run_name: 'Lower Taos Box',
    river_name: 'Rio Grande',
    state: ['NM'],
    difficulty: ['III+', 'IV'],
    permit_by_lottery: ,
    season: ['Apr', 'May', 'Jun'],
    does_it_actually_run: '',
    length_in_days: [1],
    length_in_miles: 16,
    put_in: '',
    take_out: '',
    gauge: 'https://waterdata.usgs.gov/monitoring-location/08276500/#parameterCode=00060&period=P7D',
    recommended_flows: '',
    img: '',
    img_credit: '',
    link_to_more_info: '',
    facts: [''],
    wild_and_scenic: false
  },
  {
    id: 40,
    run_name: 'Tuolumne',
    river_name: '',
    state: [''],
    difficulty: '',
    permit_by_lottery: ,
    season: [],
    does_it_actually_run: '',
    length_in_days: [],
    length_in_miles: ,
    put_in: '',
    take_out: '',
    gauge: '',
    recommended_flows: '',
    img: '',
    img_credit: '',
    link_to_more_info: '',
    facts: [''],
    wild_and_scenic:
  },
  v
  {
    id: 41,
    run_name: 'Lochsa',
    river_name: '',
    state: [''],
    difficulty: '',
    permit_by_lottery: ,
    season: [],
    does_it_actually_run: '',
    length_in_days: [],
    length_in_miles: ,
    put_in: '',
    take_out: '',
    gauge: '',
    recommended_flows: '',
    img: '',
    img_credit: '',
    link_to_more_info: '',
    facts: [''],
    wild_and_scenic:
  },
  {
    id: 42,
    run_name: 'White Salmon',
    river_name: '',
    state: [''],
    difficulty: '',
    permit_by_lottery: ,
    season: [],
    does_it_actually_run: '',
    length_in_days: [],
    length_in_miles: ,
    put_in: '',
    take_out: '',
    gauge: '',
    recommended_flows: '',
    img: '',
    img_credit: '',
    link_to_more_info: '',
    facts: [''],
    wild_and_scenic:
  },
  {
    id: 43,
    run_name: 'New River Gorge',
    river_name: '',
    state: [''],
    difficulty: '',
    permit_by_lottery: ,
    season: [],
    does_it_actually_run: '',
    length_in_days: [],
    length_in_miles: ,
    put_in: '',
    take_out: '',
    gauge: '',
    recommended_flows: '',
    img: '',
    img_credit: '',
    link_to_more_info: '',
    facts: [''],
    wild_and_scenic:
  },
  {
    id: 47,
    run_name: 'Race Course',
    river_name: 'Rio Grande',
    state: ['NM'],
    difficulty: ['III-', 'III', 'IV-'],
    permit_by_lottery: false,
    season: ['Mar', 'Apr', 'May', 'Jun'],
    does_it_actually_run: '',
    length_in_days: [0.5, 1],
    length_in_miles: 6,
    put_in: '',
    take_out: '',
    gauge: 'https://waterdata.usgs.gov/monitoring-location/08276500/#parameterCode=00060&period=P7D',
    recommended_flows: '',
    img: '',
    img_credit: '',
    link_to_more_info: '',
    facts: [''],
    wild_and_scenic: false
  }
]
