{
  rivers: [
    {
      id: 1,
      run_name: 'Upper Salt Daily',
      river_name: 'Salt',
      state: 'AZ',
      difficulty: ['III', 'IV'],
      permit_by_lottery: false,
      season: ['Feb', 'Mar', 'Apr', 'May'],
      does_it_actually_run: 'No upstream dam. It runs more often than not, but the season is short and volatile. On bad years, there might be no season, and on good years there might be a three month season at most.',
      length_in_days: [0.5, 1],
      length_in_miles: 9,
      put_in: 'Hwy 60 (First Camp) is the most popular put-in, although putting in at Baptism Rapid slightly upstream is possible at higher flows.',
      take_out: 'Hoodoo River Access',
      gauge: 'https://waterdata.usgs.gov/az/nwis/uv/?site_no=09497500&PARAmeter_cd=00065,00060',
      recommended_flows: {
        minimum: '300 cfs',
        maximum: '8,000+ cfs'
      },
      img: '',
      img_credit: '',
      link_to_more_info: '',
      facts: ['While there is no lottery system for the daily run, you will need to purchase a daily permit for each person through the White Mountain Apache Tribe.', 'There are a few sites along the river corridor that are off limits to non tribe members. Do you research, and respect this magical place.'],
      wild_and_scenic: false
    },
    {
      id: 2,
      run_name: 'Upper Salt Wilderness',
      river_name: 'Salt',
      state: 'AZ',
      difficulty: ['III', 'IV', 'IV+'],
      permit_by_lottery: true,
      season: ['Feb', 'Mar', 'Apr', 'May'],
      does_it_actually_run: 'No upstream dam. It runs more often than not, but the season is short and volatile. On bad years, there might be no season, and on good years there might be a three month season at most.',
      length_in_days: [2, 3, 4, 5],
      length_in_miles: 59,
      put_in: 'Hwy 60',
      take_out: 'Hwy 288',
      gauge: 'https://waterdata.usgs.gov/az/nwis/uv/?site_no=09497500&PARAmeter_cd=00065,00060',
      recommended_flows: {
        minimum: '350 cfs',
        maximum: '8000 cfs'
      },
      img: '',
      img_credit: '',
      link_to_more_info: '',
      facts: ['There are a few sites along the river corridor that are off limits to non tribe members. Do you research, and respect this magical place.'],
      wild_and_scenic: false
    },
    {
      id: 3,
      run_name: 'Browns Canyon National Monument',
      river_name: 'Arkansas',
      state: 'CO',
      difficulty: ['III', 'IV'],
      permit_by_lottery: false,
      season: ['May', 'Jun', 'Jul', 'Aug', 'Sept'],
      does_it_actually_run: 'This section reliably runs each summer due to the Voluntary Flow Management Program, although it usually drops to only the native flow around mid August. During some seasons, the native flow still makes for a fun trip, but during others this will mean very low water.',
      length_in_days: [0.5, 1, 2],
      length_in_miles: 13,
      put_in: 'There are several options, although most boaters start in the town of Nathrop, CO. Fisherman\'s Bridge and Ruby Mountain are the most popular access points. Trip distance is calculated to Stone Bridge',
      take_out: 'Hecla Junction and Stone Bridge are the most popular take-outs.',
      gauge: 'https://waterdata.usgs.gov/nwis/uv?07091200',
      recommended_flows: {
        minimum: '250 cfs',
        maximum: '5500 cfs'
      },
      img: '',
      img_credit: '',
      link_to_more_info: '',
      facts: ['The recommended flows are quite generous. If you\'re unfamiliar with the run you will likely get hung up on the low end, and the high end will be quite exciting.', 'There are many spots for camping along the river corridor if you plan to make this a two day trip. Be aware that many of these sites will be occupied by commercial trips during peak season and weekends.'],
      wild_and_scenic: false
    },
    {
      id: 4,
      run_name: 'The Numbers',
      river_name: 'Arkansas',
      state: 'CO',
      difficulty: ['IV', 'IV+'],
      permit_by_lottery: false,
      season: ['May', 'Jun', 'Jul', 'Aug', 'Sept'],
      does_it_actually_run: 'This section reliably runs each summer due to the Voluntary Flow Management Program, although it usually drops to only the native flow around mid August. During some seasons, the native flow still makes for a fun trip, but during others this will mean very low water.',
      length_in_days: [0.5],
      length_in_miles: '',
      put_in: 'There is a developed put-in located on HWY 24 (Numbers River Access), and an unofficial put-in slightly north. Look for a small dirt lot.',
      take_out: 'There is a stealth take-out river left after Rapid 5. The official take-outs are Miner\'s River Access and Railroad Bridge River Access.',
      gauge: 'https://waterdata.usgs.gov/nwis/uv?07091200',
      recommended_flows: {
        minimum: '300 cfs',
        maximum: '3000 cfs'
      },
      img: '',
      img_credit: '',
      link_to_more_info: '',
      facts: [''],
      wild_and_scenic: false
    },
    {
      id: 5,
      run_name: 'The Royal Gorge',
      river_name: 'Arkansas',
      state: 'CO',
      difficulty: ['IV', 'IV+'],
      permit_by_lottery: false,
      season: ['May', 'Jun', 'Jul', 'Aug', 'Sept'],
      does_it_actually_run: 'This section reliably runs each summer due to the Voluntary Flow Management Program, although it usually drops to only the native flow around mid August. During some seasons, the native flow still makes for a fun trip, but during others this will mean very low water.',
      length_in_days: [0.5, 1],
      length_in_miles: 10,
      put_in: 'Parkdale River Access',
      take_out: 'Centennial Park (Canon City Whitewater Park)',
      gauge: 'https://waterdata.usgs.gov/co/nwis/uv?site_no=07094500',
      recommended_flows: {
        minimum: '300 cfs',
        maximum: '6000 cfs'
      },
      img: '',
      img_credit: '',
      link_to_more_info: '',
      facts: ['Insert bridge fact here'],
      wild_and_scenic: false
    },
    {
      id: 6,
      run_name: 'Big Horn Sheep Canyon',
      river_name: 'Arkansas',
      state: 'CO',
      difficulty: ['III'],
      permit_by_lottery: false,
      season: ['May', 'Jun', 'Jul', 'Aug', 'Sept'],
      does_it_actually_run: 'This section reliably runs each summer, although it usually drops to only the native flow around mid August. During some seasons, the native flow still makes for a fun trip, but during others this will mean very low water.',
      length_in_days: [0.5, 1],
      length_in_miles: '',
      put_in: '',
      take_out: '',
      gauge: '',
      recommended_flows: '',
      img: '',
      img_credit: '',
      link_to_more_info: '',
      facts: [''],
      wild_and_scenic: false
    },
    {
      id: 7,
      run_name: 'Gates of Lodore & Echo Park',
      river_name: 'Green River',
      state: ['CO', 'UT'],
      difficulty: ['III', 'III+'],
      permit_by_lottery: true,
      season: ['Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sept'],
      does_it_actually_run: '',
      length_in_days: [3, 4, 5],
      length_in_miles: 45,
      put_in: 'Put in at the Lodore Ranger Station.',
      take_out: 'Split Mountain is the most popular take-out, although you can cut your trip short by taking out at Echo Park.',
      gauge: 'https://waterdata.usgs.gov/ut/nwis/uv/?site_no=09234500&PARAmeter_cd=00065,00060,72020,00010,00095,00300,63680',
      recommended_flows: {
        minimum: '800 cfs',
        maximum: '7000 cfs'
      },
      img: '',
      img_credit: '',
      link_to_more_info: '',
      facts: ['Rainbow Park to Split Mountain can be run as a day trip.'],
      wild_and_scenic: false
    },
    {
      id: 8,
      run_name: 'Rio Chama Wilderness',
      river_name: 'Rio Chama',
      state: ['CO'],
      difficulty: ['II', 'III'],
      permit_by_lottery: true,
      season: [],
      does_it_actually_run: '',
      length_in_days: '',
      length_in_miles: 31,
      put_in: 'Cooper\'s El Vado Ranch',
      take_out: 'Big Eddy',
      gauge: '',
      recommended_flows: '',
      img: '',
      img_credit: '',
      link_to_more_info: '',
      facts: [''],
      wild_and_scenic: true
    },
    {
      id: 9,
      run_name: 'San Juan',
      river_name: '',
      state: '',
      difficulty: '',
      permit_by_lottery: ,
      season: [],
      does_it_actually_run: '',
      length_in_days: '',
      length_in_miles: '',
      put_in: '',
      take_out: '',
      gauge: '',
      recommended_flows: '',
      img: '',
      img_credit: '',
      link_to_more_info: '',
      facts: ['']
    },
    {
      id: 10,
      run_name: 'Westwater',
      river_name: '',
      state: '',
      difficulty: '',
      permit_by_lottery: ,
      season: [],
      does_it_actually_run: '',
      length_in_days: '',
      length_in_miles: '',
      put_in: '',
      take_out: '',
      gauge: '',
      recommended_flows: '',
      img: '',
      img_credit: '',
      link_to_more_info: '',
      facts: ['']
    },
    {
      id: 11,
      run_name: 'Ruby Horsethief',
      river_name: '',
      state: '',
      difficulty: '',
      permit_by_lottery: ,
      season: [],
      does_it_actually_run: '',
      length_in_days: '',
      length_in_miles: '',
      put_in: '',
      take_out: '',
      gauge: '',
      recommended_flows: '',
      img: '',
      img_credit: '',
      link_to_more_info: '',
      facts: ['']
    },
    {
      id: 12,
      run_name: 'Yampa',
      river_name: 'Yampa River',
      state: ['CO', 'UT'],
      difficulty: '',
      permit_by_lottery: ,
      season: ['May', 'Jun', 'Jul'],
      does_it_actually_run: '',
      length_in_days: '',
      length_in_miles: '',
      put_in: 'Deerlodge Park',
      take_out: 'Split Mountain.',
      gauge: '',
      recommended_flows: '',
      img: '',
      img_credit: '',
      link_to_more_info: '',
      facts: ['']
    },
    {
      id: 13,
      run_name: 'Gunnison Gorge',
      river_name: 'Gunnison River',
      state: ['CO'],
      difficulty: 'III - III+',
      permit_by_lottery: ,
      season: [],
      does_it_actually_run: '',
      length_in_days: '1-2',
      length_in_miles: '',
      put_in: 'Chukar Boat Ramp - accessed via a primitive road followed by a mile long hike in.',
      take_out: '',
      gauge: '',
      recommended_flows: '',
      img: '',
      img_credit: '',
      link_to_more_info: 'https://www.blm.gov/sites/blm.gov/files/River%20Map%20in%20PDF%20for%20web.pdf',
      facts: ['If you choose to rent mules to help with the gear carry in, contact J and R Outfitters.']
    },
    {
      id: 14,
      run_name: 'Cataract Canyon',
      river_name: '',
      state: '',
      difficulty: '',
      permit_by_lottery: ,
      season: [],
      does_it_actually_run: '',
      length_in_days: '',
      length_in_miles: '',
      put_in: '',
      take_out: '',
      gauge: '',
      recommended_flows: '',
      img: '',
      img_credit: '',
      link_to_more_info: '',
      facts: ['']
    },
    {
      id: 15,
      run_name: 'Desolation Gray',
      river_name: '',
      state: '',
      difficulty: '',
      permit_by_lottery: ,
      season: [],
      does_it_actually_run: '',
      length_in_days: '',
      length_in_miles: '',
      put_in: 'Sand Wash',
      take_out: 'Swasey\'s Rapid',
      gauge: '',
      recommended_flows: '',
      img: '',
      img_credit: '',
      link_to_more_info: '',
      facts: ['']
    },
    {
      id: 16,
      run_name: 'Middle Fork of the Salmon',
      river_name: '',
      state: '',
      difficulty: '',
      permit_by_lottery: ,
      season: [],
      does_it_actually_run: '',
      length_in_days: '',
      length_in_miles: '',
      put_in: '',
      take_out: '',
      gauge: '',
      recommended_flows: '',
      img: '',
      img_credit: '',
      link_to_more_info: '',
      facts: ['']
    },
    {
      id: 17,
      run_name: 'Main Fork of the Salmon',
      river_name: '',
      state: '',
      difficulty: '',
      permit_by_lottery: ,
      season: [],
      does_it_actually_run: '',
      length_in_days: '',
      length_in_miles: '',
      put_in: '',
      take_out: '',
      gauge: '',
      recommended_flows: '',
      img: '',
      img_credit: '',
      link_to_more_info: '',
      facts: ['']
    },
    {
      id: 18,
      run_name: 'Lower Salmon',
      river_name: '',
      state: '',
      difficulty: '',
      permit_by_lottery: ,
      season: [],
      does_it_actually_run: '',
      length_in_days: '',
      length_in_miles: '',
      put_in: '',
      take_out: '',
      gauge: '',
      recommended_flows: '',
      img: '',
      img_credit: '',
      link_to_more_info: '',
      facts: ['']
    },
    {
      id: 19,
      run_name: 'Grand Canyon',
      river_name: '',
      state: '',
      difficulty: '',
      permit_by_lottery: ,
      season: [],
      does_it_actually_run: '',
      length_in_days: '',
      length_in_miles: '',
      put_in: '',
      take_out: '',
      gauge: '',
      recommended_flows: '',
      img: '',
      img_credit: '',
      link_to_more_info: '',
      facts: ['']
    },
    {
      id: 20,
      run_name: 'Middle Fork of the Flathead',
      river_name: '',
      state: '',
      difficulty: '',
      permit_by_lottery: ,
      season: [],
      does_it_actually_run: '',
      length_in_days: '',
      length_in_miles: '',
      put_in: '',
      take_out: '',
      gauge: '',
      recommended_flows: '',
      img: '',
      img_credit: '',
      link_to_more_info: '',
      facts: ['']
    },
    {
      id: 21,
      run_name: 'Rouge',
      river_name: '',
      state: '',
      difficulty: '',
      permit_by_lottery: ,
      season: [],
      does_it_actually_run: '',
      length_in_days: '',
      length_in_miles: '',
      put_in: '',
      take_out: '',
      gauge: '',
      recommended_flows: '',
      img: '',
      img_credit: '',
      link_to_more_info: '',
      facts: ['']
    },
    {
      id: 22,
      run_name: 'Stillwater Canyon',
      river_name: '',
      state: '',
      difficulty: '',
      permit_by_lottery: ,
      season: [],
      does_it_actually_run: '',
      length_in_days: '',
      length_in_miles: '',
      put_in: '',
      take_out: '',
      gauge: '',
      recommended_flows: '',
      img: '',
      img_credit: '',
      link_to_more_info: '',
      facts: ['']
    },
    {
      id: 23,
      run_name: 'Labyrinth Canyon',
      river_name: '',
      state: '',
      difficulty: '',
      permit_by_lottery: ,
      season: [],
      does_it_actually_run: '',
      length_in_days: '',
      length_in_miles: '',
      put_in: '',
      take_out: '',
      gauge: '',
      recommended_flows: '',
      img: '',
      img_credit: '',
      link_to_more_info: '',
      facts: ['']
    },
    {
      id: 24,
      run_name: 'Dolores',
      river_name: '',
      state: '',
      difficulty: '',
      permit_by_lottery: ,
      season: [],
      does_it_actually_run: '',
      length_in_days: '',
      length_in_miles: '',
      put_in: '',
      take_out: '',
      gauge: '',
      recommended_flows: '',
      img: '',
      img_credit: '',
      link_to_more_info: '',
      facts: ['']
    },
    {
      id: 25,
      run_name: 'Hells Canyon',
      river_name: '',
      state: '',
      difficulty: '',
      permit_by_lottery: ,
      season: [],
      does_it_actually_run: '',
      length_in_days: '',
      length_in_miles: '',
      put_in: '',
      take_out: '',
      gauge: '',
      recommended_flows: '',
      img: '',
      img_credit: '',
      link_to_more_info: '',
      facts: ['']
    },
    {
      id: 26,
      run_name: 'Selway',
      river_name: '',
      state: '',
      difficulty: '',
      permit_by_lottery: ,
      season: [],
      does_it_actually_run: '',
      length_in_days: '',
      length_in_miles: '',
      put_in: '',
      take_out: '',
      gauge: '',
      recommended_flows: '',
      img: '',
      img_credit: '',
      link_to_more_info: '',
      facts: ['']
    },
    {
      id: 27,
      run_name: 'Moab Daily',
      river_name: '',
      state: '',
      difficulty: '',
      permit_by_lottery: ,
      season: [],
      does_it_actually_run: '',
      length_in_days: '',
      length_in_miles: '',
      put_in: '',
      take_out: '',
      gauge: '',
      recommended_flows: '',
      img: '',
      img_credit: '',
      link_to_more_info: '',
      facts: ['']
    },
    {
      id: 28,
      run_name: 'Snake',
      river_name: '',
      state: '',
      difficulty: '',
      permit_by_lottery: ,
      season: [],
      does_it_actually_run: '',
      length_in_days: '',
      length_in_miles: '',
      put_in: '',
      take_out: '',
      gauge: '',
      recommended_flows: '',
      img: '',
      img_credit: '',
      link_to_more_info: '',
      facts: ['']
    },
    {
      id: 29,
      run_name: 'The Fractions',
      river_name: 'Arkansas',
      state: '',
      difficulty: '',
      permit_by_lottery: false,
      season: [],
      does_it_actually_run: '',
      length_in_days: '',
      length_in_miles: '',
      put_in: '',
      take_out: '',
      gauge: '',
      recommended_flows: '',
      img: '',
      img_credit: '',
      link_to_more_info: '',
      facts: ['']
    },
    {
      id: 30,
      run_name: '',
      river_name: '',
      state: '',
      difficulty: '',
      permit_by_lottery: ,
      season: [],
      does_it_actually_run: '',
      length_in_days: '',
      length_in_miles: '',
      put_in: '',
      take_out: '',
      gauge: '',
      recommended_flows: '',
      img: '',
      img_credit: '',
      link_to_more_info: '',
      facts: ['']
    }
  ]
}

// Owyhee, Chattooga, South fork of salmon, illinois, Middle fork of Flathead, John Day, Smith, Nolichucky, Watauga Gorge, milk run
//
